# -*- coding: utf-8 -*-
# pylint: skip-file

################################################################################
## Form generated from reading UI file 'sudoku_grid_plainBjLcDC.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(900, 700)
        Form.setStyleSheet(u"")
        self.le_00 = QLineEdit(Form)
        self.le_00.setObjectName(u"le_00")
        self.le_00.setGeometry(QRect(180, 80, 60, 60))
        font = QFont()
        font.setPointSize(24)
        self.le_00.setFont(font)
        self.le_00.setStyleSheet(u"\n"
"QLineEdit:focus {\n"
"	background-color: rgb(163, 223, 249);\n"
"}")
        self.le_00.setAlignment(Qt.AlignCenter)
        self.line_2 = QFrame(Form)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(180, 620, 540, 3))
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_5 = QFrame(Form)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(180, 440, 540, 3))
        self.line_5.setStyleSheet(u"color: rgb(0, 127, 191);")
        self.line_5.setFrameShadow(QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_6 = QFrame(Form)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(180, 380, 540, 3))
        self.line_6.setStyleSheet(u"color: rgb(155, 203, 255);")
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_6.setLineWidth(1)
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_7 = QFrame(Form)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(180, 320, 540, 3))
        self.line_7.setStyleSheet(u"color: rgb(155, 203, 255);")
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_7.setLineWidth(1)
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_10 = QFrame(Form)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(180, 500, 540, 3))
        self.line_10.setStyleSheet(u"color: rgb(155, 203, 255);")
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_10.setLineWidth(1)
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_11 = QFrame(Form)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(180, 560, 540, 3))
        self.line_11.setStyleSheet(u"color: rgb(155, 203, 255);")
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line_11.setLineWidth(1)
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_12 = QFrame(Form)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(720, 80, 3, 540))
        self.line_12.setFrameShadow(QFrame.Plain)
        self.line_12.setLineWidth(3)
        self.line_12.setFrameShape(QFrame.VLine)
        self.line_14 = QFrame(Form)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(540, 80, 3, 540))
        self.line_14.setStyleSheet(u"color: rgb(0, 127, 191);")
        self.line_14.setFrameShadow(QFrame.Plain)
        self.line_14.setLineWidth(3)
        self.line_14.setFrameShape(QFrame.VLine)
        self.line_17 = QFrame(Form)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(420, 80, 3, 540))
        self.line_17.setFrameShadow(QFrame.Sunken)
        self.line_17.setLineWidth(1)
        self.line_17.setFrameShape(QFrame.VLine)
        self.line_18 = QFrame(Form)
        self.line_18.setObjectName(u"line_18")
        self.line_18.setGeometry(QRect(480, 80, 3, 540))
        self.line_18.setFrameShadow(QFrame.Sunken)
        self.line_18.setLineWidth(1)
        self.line_18.setFrameShape(QFrame.VLine)
        self.line_19 = QFrame(Form)
        self.line_19.setObjectName(u"line_19")
        self.line_19.setGeometry(QRect(600, 80, 3, 540))
        self.line_19.setFrameShadow(QFrame.Sunken)
        self.line_19.setLineWidth(1)
        self.line_19.setFrameShape(QFrame.VLine)
        self.line_20 = QFrame(Form)
        self.line_20.setObjectName(u"line_20")
        self.line_20.setGeometry(QRect(660, 80, 3, 540))
        self.line_20.setFrameShadow(QFrame.Sunken)
        self.line_20.setLineWidth(1)
        self.line_20.setFrameShape(QFrame.VLine)
        self.le_01 = QLineEdit(Form)
        self.le_01.setObjectName(u"le_01")
        self.le_01.setGeometry(QRect(240, 80, 60, 60))
        self.le_01.setFont(font)
        self.le_01.setAlignment(Qt.AlignCenter)
        self.le_02 = QLineEdit(Form)
        self.le_02.setObjectName(u"le_02")
        self.le_02.setGeometry(QRect(300, 80, 60, 60))
        self.le_02.setFont(font)
        self.le_02.setAlignment(Qt.AlignCenter)
        self.le_10 = QLineEdit(Form)
        self.le_10.setObjectName(u"le_10")
        self.le_10.setGeometry(QRect(180, 140, 60, 60))
        self.le_10.setFont(font)
        self.le_10.setAlignment(Qt.AlignCenter)
        self.le_11 = QLineEdit(Form)
        self.le_11.setObjectName(u"le_11")
        self.le_11.setGeometry(QRect(240, 140, 60, 60))
        self.le_11.setFont(font)
        self.le_11.setAlignment(Qt.AlignCenter)
        self.le_12 = QLineEdit(Form)
        self.le_12.setObjectName(u"le_12")
        self.le_12.setGeometry(QRect(300, 140, 60, 60))
        self.le_12.setFont(font)
        self.le_12.setAlignment(Qt.AlignCenter)
        self.le_20 = QLineEdit(Form)
        self.le_20.setObjectName(u"le_20")
        self.le_20.setGeometry(QRect(180, 200, 60, 60))
        self.le_20.setFont(font)
        self.le_20.setAlignment(Qt.AlignCenter)
        self.le_21 = QLineEdit(Form)
        self.le_21.setObjectName(u"le_21")
        self.le_21.setGeometry(QRect(240, 200, 60, 60))
        self.le_21.setFont(font)
        self.le_21.setAlignment(Qt.AlignCenter)
        self.le_22 = QLineEdit(Form)
        self.le_22.setObjectName(u"le_22")
        self.le_22.setGeometry(QRect(300, 200, 60, 60))
        self.le_22.setFont(font)
        self.le_22.setAlignment(Qt.AlignCenter)
        self.le_14 = QLineEdit(Form)
        self.le_14.setObjectName(u"le_14")
        self.le_14.setGeometry(QRect(420, 140, 60, 60))
        self.le_14.setFont(font)
        self.le_14.setAlignment(Qt.AlignCenter)
        self.le_03 = QLineEdit(Form)
        self.le_03.setObjectName(u"le_03")
        self.le_03.setGeometry(QRect(360, 80, 60, 60))
        self.le_03.setFont(font)
        self.le_03.setAlignment(Qt.AlignCenter)
        self.le_25 = QLineEdit(Form)
        self.le_25.setObjectName(u"le_25")
        self.le_25.setGeometry(QRect(480, 200, 60, 60))
        self.le_25.setFont(font)
        self.le_25.setAlignment(Qt.AlignCenter)
        self.le_04 = QLineEdit(Form)
        self.le_04.setObjectName(u"le_04")
        self.le_04.setGeometry(QRect(420, 80, 60, 60))
        self.le_04.setFont(font)
        self.le_04.setAlignment(Qt.AlignCenter)
        self.le_24 = QLineEdit(Form)
        self.le_24.setObjectName(u"le_24")
        self.le_24.setGeometry(QRect(420, 200, 60, 60))
        self.le_24.setFont(font)
        self.le_24.setAlignment(Qt.AlignCenter)
        self.le_05 = QLineEdit(Form)
        self.le_05.setObjectName(u"le_05")
        self.le_05.setGeometry(QRect(480, 80, 60, 60))
        self.le_05.setFont(font)
        self.le_05.setAlignment(Qt.AlignCenter)
        self.le_15 = QLineEdit(Form)
        self.le_15.setObjectName(u"le_15")
        self.le_15.setGeometry(QRect(480, 140, 60, 60))
        self.le_15.setFont(font)
        self.le_15.setAlignment(Qt.AlignCenter)
        self.le_23 = QLineEdit(Form)
        self.le_23.setObjectName(u"le_23")
        self.le_23.setGeometry(QRect(360, 200, 60, 60))
        self.le_23.setFont(font)
        self.le_23.setAlignment(Qt.AlignCenter)
        self.le_13 = QLineEdit(Form)
        self.le_13.setObjectName(u"le_13")
        self.le_13.setGeometry(QRect(360, 140, 60, 60))
        self.le_13.setFont(font)
        self.le_13.setAlignment(Qt.AlignCenter)
        self.le_17 = QLineEdit(Form)
        self.le_17.setObjectName(u"le_17")
        self.le_17.setGeometry(QRect(600, 140, 60, 60))
        self.le_17.setFont(font)
        self.le_17.setAlignment(Qt.AlignCenter)
        self.le_06 = QLineEdit(Form)
        self.le_06.setObjectName(u"le_06")
        self.le_06.setGeometry(QRect(540, 80, 60, 60))
        self.le_06.setFont(font)
        self.le_06.setAlignment(Qt.AlignCenter)
        self.le_28 = QLineEdit(Form)
        self.le_28.setObjectName(u"le_28")
        self.le_28.setGeometry(QRect(660, 200, 60, 60))
        self.le_28.setFont(font)
        self.le_28.setAlignment(Qt.AlignCenter)
        self.le_07 = QLineEdit(Form)
        self.le_07.setObjectName(u"le_07")
        self.le_07.setGeometry(QRect(600, 80, 60, 60))
        self.le_07.setFont(font)
        self.le_07.setAlignment(Qt.AlignCenter)
        self.le_27 = QLineEdit(Form)
        self.le_27.setObjectName(u"le_27")
        self.le_27.setGeometry(QRect(600, 200, 60, 60))
        self.le_27.setFont(font)
        self.le_27.setAlignment(Qt.AlignCenter)
        self.le_08 = QLineEdit(Form)
        self.le_08.setObjectName(u"le_08")
        self.le_08.setGeometry(QRect(660, 80, 60, 60))
        self.le_08.setFont(font)
        self.le_08.setAlignment(Qt.AlignCenter)
        self.le_18 = QLineEdit(Form)
        self.le_18.setObjectName(u"le_18")
        self.le_18.setGeometry(QRect(660, 140, 60, 60))
        self.le_18.setFont(font)
        self.le_18.setAlignment(Qt.AlignCenter)
        self.le_26 = QLineEdit(Form)
        self.le_26.setObjectName(u"le_26")
        self.le_26.setGeometry(QRect(540, 200, 60, 60))
        self.le_26.setFont(font)
        self.le_26.setAlignment(Qt.AlignCenter)
        self.le_16 = QLineEdit(Form)
        self.le_16.setObjectName(u"le_16")
        self.le_16.setGeometry(QRect(540, 140, 60, 60))
        self.le_16.setFont(font)
        self.le_16.setAlignment(Qt.AlignCenter)
        self.le_47 = QLineEdit(Form)
        self.le_47.setObjectName(u"le_47")
        self.le_47.setGeometry(QRect(600, 320, 60, 60))
        self.le_47.setFont(font)
        self.le_47.setAlignment(Qt.AlignCenter)
        self.le_36 = QLineEdit(Form)
        self.le_36.setObjectName(u"le_36")
        self.le_36.setGeometry(QRect(540, 260, 60, 60))
        self.le_36.setFont(font)
        self.le_36.setAlignment(Qt.AlignCenter)
        self.le_58 = QLineEdit(Form)
        self.le_58.setObjectName(u"le_58")
        self.le_58.setGeometry(QRect(660, 380, 60, 60))
        self.le_58.setFont(font)
        self.le_58.setAlignment(Qt.AlignCenter)
        self.le_37 = QLineEdit(Form)
        self.le_37.setObjectName(u"le_37")
        self.le_37.setGeometry(QRect(600, 260, 60, 60))
        self.le_37.setFont(font)
        self.le_37.setAlignment(Qt.AlignCenter)
        self.le_57 = QLineEdit(Form)
        self.le_57.setObjectName(u"le_57")
        self.le_57.setGeometry(QRect(600, 380, 60, 60))
        self.le_57.setFont(font)
        self.le_57.setAlignment(Qt.AlignCenter)
        self.le_38 = QLineEdit(Form)
        self.le_38.setObjectName(u"le_38")
        self.le_38.setGeometry(QRect(660, 260, 60, 60))
        self.le_38.setFont(font)
        self.le_38.setAlignment(Qt.AlignCenter)
        self.le_48 = QLineEdit(Form)
        self.le_48.setObjectName(u"le_48")
        self.le_48.setGeometry(QRect(660, 320, 60, 60))
        self.le_48.setFont(font)
        self.le_48.setAlignment(Qt.AlignCenter)
        self.le_56 = QLineEdit(Form)
        self.le_56.setObjectName(u"le_56")
        self.le_56.setGeometry(QRect(540, 380, 60, 60))
        self.le_56.setFont(font)
        self.le_56.setAlignment(Qt.AlignCenter)
        self.le_46 = QLineEdit(Form)
        self.le_46.setObjectName(u"le_46")
        self.le_46.setGeometry(QRect(540, 320, 60, 60))
        self.le_46.setFont(font)
        self.le_46.setAlignment(Qt.AlignCenter)
        self.le_44 = QLineEdit(Form)
        self.le_44.setObjectName(u"le_44")
        self.le_44.setGeometry(QRect(420, 320, 60, 60))
        self.le_44.setFont(font)
        self.le_44.setAlignment(Qt.AlignCenter)
        self.le_33 = QLineEdit(Form)
        self.le_33.setObjectName(u"le_33")
        self.le_33.setGeometry(QRect(360, 260, 60, 60))
        self.le_33.setFont(font)
        self.le_33.setAlignment(Qt.AlignCenter)
        self.le_55 = QLineEdit(Form)
        self.le_55.setObjectName(u"le_55")
        self.le_55.setGeometry(QRect(480, 380, 60, 60))
        self.le_55.setFont(font)
        self.le_55.setAlignment(Qt.AlignCenter)
        self.le_34 = QLineEdit(Form)
        self.le_34.setObjectName(u"le_34")
        self.le_34.setGeometry(QRect(420, 260, 60, 60))
        self.le_34.setFont(font)
        self.le_34.setAlignment(Qt.AlignCenter)
        self.le_54 = QLineEdit(Form)
        self.le_54.setObjectName(u"le_54")
        self.le_54.setGeometry(QRect(420, 380, 60, 60))
        self.le_54.setFont(font)
        self.le_54.setAlignment(Qt.AlignCenter)
        self.le_35 = QLineEdit(Form)
        self.le_35.setObjectName(u"le_35")
        self.le_35.setGeometry(QRect(480, 260, 60, 60))
        self.le_35.setFont(font)
        self.le_35.setAlignment(Qt.AlignCenter)
        self.le_45 = QLineEdit(Form)
        self.le_45.setObjectName(u"le_45")
        self.le_45.setGeometry(QRect(480, 320, 60, 60))
        self.le_45.setFont(font)
        self.le_45.setAlignment(Qt.AlignCenter)
        self.le_53 = QLineEdit(Form)
        self.le_53.setObjectName(u"le_53")
        self.le_53.setGeometry(QRect(360, 380, 60, 60))
        self.le_53.setFont(font)
        self.le_53.setAlignment(Qt.AlignCenter)
        self.le_43 = QLineEdit(Form)
        self.le_43.setObjectName(u"le_43")
        self.le_43.setGeometry(QRect(360, 320, 60, 60))
        self.le_43.setFont(font)
        self.le_43.setAlignment(Qt.AlignCenter)
        self.le_41 = QLineEdit(Form)
        self.le_41.setObjectName(u"le_41")
        self.le_41.setGeometry(QRect(240, 320, 60, 60))
        self.le_41.setFont(font)
        self.le_41.setAlignment(Qt.AlignCenter)
        self.le_30 = QLineEdit(Form)
        self.le_30.setObjectName(u"le_30")
        self.le_30.setGeometry(QRect(180, 260, 60, 60))
        self.le_30.setFont(font)
        self.le_30.setAlignment(Qt.AlignCenter)
        self.le_52 = QLineEdit(Form)
        self.le_52.setObjectName(u"le_52")
        self.le_52.setGeometry(QRect(300, 380, 60, 60))
        self.le_52.setFont(font)
        self.le_52.setAlignment(Qt.AlignCenter)
        self.le_31 = QLineEdit(Form)
        self.le_31.setObjectName(u"le_31")
        self.le_31.setGeometry(QRect(240, 260, 60, 60))
        self.le_31.setFont(font)
        self.le_31.setAlignment(Qt.AlignCenter)
        self.le_51 = QLineEdit(Form)
        self.le_51.setObjectName(u"le_51")
        self.le_51.setGeometry(QRect(240, 380, 60, 60))
        self.le_51.setFont(font)
        self.le_51.setAlignment(Qt.AlignCenter)
        self.le_32 = QLineEdit(Form)
        self.le_32.setObjectName(u"le_32")
        self.le_32.setGeometry(QRect(300, 260, 60, 60))
        self.le_32.setFont(font)
        self.le_32.setAlignment(Qt.AlignCenter)
        self.le_42 = QLineEdit(Form)
        self.le_42.setObjectName(u"le_42")
        self.le_42.setGeometry(QRect(300, 320, 60, 60))
        self.le_42.setFont(font)
        self.le_42.setAlignment(Qt.AlignCenter)
        self.le_50 = QLineEdit(Form)
        self.le_50.setObjectName(u"le_50")
        self.le_50.setGeometry(QRect(180, 380, 60, 60))
        self.le_50.setFont(font)
        self.le_50.setAlignment(Qt.AlignCenter)
        self.le_40 = QLineEdit(Form)
        self.le_40.setObjectName(u"le_40")
        self.le_40.setGeometry(QRect(180, 320, 60, 60))
        self.le_40.setFont(font)
        self.le_40.setAlignment(Qt.AlignCenter)
        self.le_71 = QLineEdit(Form)
        self.le_71.setObjectName(u"le_71")
        self.le_71.setGeometry(QRect(240, 500, 60, 60))
        self.le_71.setFont(font)
        self.le_71.setAlignment(Qt.AlignCenter)
        self.le_60 = QLineEdit(Form)
        self.le_60.setObjectName(u"le_60")
        self.le_60.setGeometry(QRect(180, 440, 60, 60))
        self.le_60.setFont(font)
        self.le_60.setAlignment(Qt.AlignCenter)
        self.le_82 = QLineEdit(Form)
        self.le_82.setObjectName(u"le_82")
        self.le_82.setGeometry(QRect(300, 560, 60, 60))
        self.le_82.setFont(font)
        self.le_82.setAlignment(Qt.AlignCenter)
        self.le_61 = QLineEdit(Form)
        self.le_61.setObjectName(u"le_61")
        self.le_61.setGeometry(QRect(240, 440, 60, 60))
        self.le_61.setFont(font)
        self.le_61.setAlignment(Qt.AlignCenter)
        self.le_81 = QLineEdit(Form)
        self.le_81.setObjectName(u"le_81")
        self.le_81.setGeometry(QRect(240, 560, 60, 60))
        self.le_81.setFont(font)
        self.le_81.setAlignment(Qt.AlignCenter)
        self.le_62 = QLineEdit(Form)
        self.le_62.setObjectName(u"le_62")
        self.le_62.setGeometry(QRect(300, 440, 60, 60))
        self.le_62.setFont(font)
        self.le_62.setAlignment(Qt.AlignCenter)
        self.le_72 = QLineEdit(Form)
        self.le_72.setObjectName(u"le_72")
        self.le_72.setGeometry(QRect(300, 500, 60, 60))
        self.le_72.setFont(font)
        self.le_72.setAlignment(Qt.AlignCenter)
        self.le_80 = QLineEdit(Form)
        self.le_80.setObjectName(u"le_80")
        self.le_80.setGeometry(QRect(180, 560, 60, 60))
        self.le_80.setFont(font)
        self.le_80.setAlignment(Qt.AlignCenter)
        self.le_70 = QLineEdit(Form)
        self.le_70.setObjectName(u"le_70")
        self.le_70.setGeometry(QRect(180, 500, 60, 60))
        self.le_70.setFont(font)
        self.le_70.setAlignment(Qt.AlignCenter)
        self.le_74 = QLineEdit(Form)
        self.le_74.setObjectName(u"le_74")
        self.le_74.setGeometry(QRect(420, 500, 60, 60))
        self.le_74.setFont(font)
        self.le_74.setAlignment(Qt.AlignCenter)
        self.le_63 = QLineEdit(Form)
        self.le_63.setObjectName(u"le_63")
        self.le_63.setGeometry(QRect(360, 440, 60, 60))
        self.le_63.setFont(font)
        self.le_63.setAlignment(Qt.AlignCenter)
        self.le_85 = QLineEdit(Form)
        self.le_85.setObjectName(u"le_85")
        self.le_85.setGeometry(QRect(480, 560, 60, 60))
        self.le_85.setFont(font)
        self.le_85.setAlignment(Qt.AlignCenter)
        self.le_64 = QLineEdit(Form)
        self.le_64.setObjectName(u"le_64")
        self.le_64.setGeometry(QRect(420, 440, 60, 60))
        self.le_64.setFont(font)
        self.le_64.setAlignment(Qt.AlignCenter)
        self.le_84 = QLineEdit(Form)
        self.le_84.setObjectName(u"le_84")
        self.le_84.setGeometry(QRect(420, 560, 60, 60))
        self.le_84.setFont(font)
        self.le_84.setAlignment(Qt.AlignCenter)
        self.le_65 = QLineEdit(Form)
        self.le_65.setObjectName(u"le_65")
        self.le_65.setGeometry(QRect(480, 440, 60, 60))
        self.le_65.setFont(font)
        self.le_65.setAlignment(Qt.AlignCenter)
        self.le_75 = QLineEdit(Form)
        self.le_75.setObjectName(u"le_75")
        self.le_75.setGeometry(QRect(480, 500, 60, 60))
        self.le_75.setFont(font)
        self.le_75.setAlignment(Qt.AlignCenter)
        self.le_83 = QLineEdit(Form)
        self.le_83.setObjectName(u"le_83")
        self.le_83.setGeometry(QRect(360, 560, 60, 60))
        self.le_83.setFont(font)
        self.le_83.setAlignment(Qt.AlignCenter)
        self.le_73 = QLineEdit(Form)
        self.le_73.setObjectName(u"le_73")
        self.le_73.setGeometry(QRect(360, 500, 60, 60))
        self.le_73.setFont(font)
        self.le_73.setAlignment(Qt.AlignCenter)
        self.le_77 = QLineEdit(Form)
        self.le_77.setObjectName(u"le_77")
        self.le_77.setGeometry(QRect(600, 500, 60, 60))
        self.le_77.setFont(font)
        self.le_77.setAlignment(Qt.AlignCenter)
        self.le_66 = QLineEdit(Form)
        self.le_66.setObjectName(u"le_66")
        self.le_66.setGeometry(QRect(540, 440, 60, 60))
        self.le_66.setFont(font)
        self.le_66.setAlignment(Qt.AlignCenter)
        self.le_88 = QLineEdit(Form)
        self.le_88.setObjectName(u"le_88")
        self.le_88.setGeometry(QRect(660, 560, 60, 60))
        self.le_88.setFont(font)
        self.le_88.setAlignment(Qt.AlignCenter)
        self.le_67 = QLineEdit(Form)
        self.le_67.setObjectName(u"le_67")
        self.le_67.setGeometry(QRect(600, 440, 60, 60))
        self.le_67.setFont(font)
        self.le_67.setAlignment(Qt.AlignCenter)
        self.le_87 = QLineEdit(Form)
        self.le_87.setObjectName(u"le_87")
        self.le_87.setGeometry(QRect(600, 560, 60, 60))
        self.le_87.setFont(font)
        self.le_87.setAlignment(Qt.AlignCenter)
        self.le_68 = QLineEdit(Form)
        self.le_68.setObjectName(u"le_68")
        self.le_68.setGeometry(QRect(660, 440, 60, 60))
        self.le_68.setFont(font)
        self.le_68.setAlignment(Qt.AlignCenter)
        self.le_78 = QLineEdit(Form)
        self.le_78.setObjectName(u"le_78")
        self.le_78.setGeometry(QRect(660, 500, 60, 60))
        self.le_78.setFont(font)
        self.le_78.setAlignment(Qt.AlignCenter)
        self.le_86 = QLineEdit(Form)
        self.le_86.setObjectName(u"le_86")
        self.le_86.setGeometry(QRect(540, 560, 60, 60))
        self.le_86.setFont(font)
        self.le_86.setAlignment(Qt.AlignCenter)
        self.le_76 = QLineEdit(Form)
        self.le_76.setObjectName(u"le_76")
        self.le_76.setGeometry(QRect(540, 500, 60, 60))
        self.le_76.setFont(font)
        self.le_76.setAlignment(Qt.AlignCenter)
        self.line_8 = QFrame(Form)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(180, 80, 3, 540))
        self.line_8.setFrameShadow(QFrame.Plain)
        self.line_8.setLineWidth(3)
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(180, 80, 540, 3))
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_16 = QFrame(Form)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(240, 80, 3, 540))
        self.line_16.setFrameShadow(QFrame.Sunken)
        self.line_16.setLineWidth(1)
        self.line_16.setFrameShape(QFrame.VLine)
        self.line_21 = QFrame(Form)
        self.line_21.setObjectName(u"line_21")
        self.line_21.setGeometry(QRect(300, 80, 3, 540))
        self.line_21.setFrameShadow(QFrame.Sunken)
        self.line_21.setLineWidth(1)
        self.line_21.setFrameShape(QFrame.VLine)
        self.line_22 = QFrame(Form)
        self.line_22.setObjectName(u"line_22")
        self.line_22.setGeometry(QRect(420, 80, 3, 540))
        self.line_22.setFrameShadow(QFrame.Sunken)
        self.line_22.setLineWidth(1)
        self.line_22.setFrameShape(QFrame.VLine)
        self.line_23 = QFrame(Form)
        self.line_23.setObjectName(u"line_23")
        self.line_23.setGeometry(QRect(480, 80, 3, 540))
        self.line_23.setFrameShadow(QFrame.Sunken)
        self.line_23.setLineWidth(1)
        self.line_23.setFrameShape(QFrame.VLine)
        self.line_24 = QFrame(Form)
        self.line_24.setObjectName(u"line_24")
        self.line_24.setGeometry(QRect(660, 80, 3, 540))
        self.line_24.setFrameShadow(QFrame.Sunken)
        self.line_24.setLineWidth(1)
        self.line_24.setFrameShape(QFrame.VLine)
        self.line_25 = QFrame(Form)
        self.line_25.setObjectName(u"line_25")
        self.line_25.setGeometry(QRect(600, 80, 3, 540))
        self.line_25.setFrameShadow(QFrame.Sunken)
        self.line_25.setLineWidth(1)
        self.line_25.setFrameShape(QFrame.VLine)
        self.line_26 = QFrame(Form)
        self.line_26.setObjectName(u"line_26")
        self.line_26.setGeometry(QRect(180, 260, 540, 3))
        self.line_26.setStyleSheet(u"color: rgb(0, 127, 191);")
        self.line_26.setFrameShadow(QFrame.Plain)
        self.line_26.setLineWidth(3)
        self.line_26.setFrameShape(QFrame.HLine)
        self.line_27 = QFrame(Form)
        self.line_27.setObjectName(u"line_27")
        self.line_27.setGeometry(QRect(180, 440, 540, 3))
        self.line_27.setStyleSheet(u"color: rgb(0, 127, 191);")
        self.line_27.setFrameShadow(QFrame.Plain)
        self.line_27.setLineWidth(3)
        self.line_27.setFrameShape(QFrame.HLine)
        self.line_28 = QFrame(Form)
        self.line_28.setObjectName(u"line_28")
        self.line_28.setGeometry(QRect(360, 80, 3, 540))
        self.line_28.setStyleSheet(u"color: rgb(0, 127, 191);")
        self.line_28.setFrameShadow(QFrame.Plain)
        self.line_28.setLineWidth(3)
        self.line_28.setFrameShape(QFrame.VLine)
        self.line_29 = QFrame(Form)
        self.line_29.setObjectName(u"line_29")
        self.line_29.setGeometry(QRect(540, 80, 3, 540))
        self.line_29.setStyleSheet(u"color: rgb(0, 127, 191);")
        self.line_29.setFrameShadow(QFrame.Plain)
        self.line_29.setLineWidth(3)
        self.line_29.setFrameShape(QFrame.VLine)
        self.return_button = QPushButton(Form)
        self.return_button.setObjectName(u"return_button")
        self.return_button.setGeometry(QRect(20, 20, 101, 61))
        self.return_button.setStyleSheet(u"background-color: rgb(255, 170, 0);\n"
"font: 9pt \"Tempus Sans ITC\";")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.return_button.setText(QCoreApplication.translate("Form", u"Return to \n"
" main menu", None))
    # retranslateUi

